/**
 * Created by yuyou on 14/11/3.
 * Discribe: motion script file
 */
var config = {
    basic:{
        js:[
            {
                name:"jquery",
                url:"jquery.js",
                sync:true
            },
            {
                name:"swip",
                url:"jquery.suno_swip.js",
                sync:false
            },
            {
                name:"pager",
                url:"jquery.suno_pager.js",
                sync:false
            },
            {
                name:"move",
                url:"jquery.suno_move.js",
                sync:false
            },
            {
                name:"exec",
                url:"exec.js",
                sync:false
            }
        ]
    },
    pages:[
        {
            id:"page_1",
            config:{
                gravity:true
            },
            fill:["rgba(0,0,0,0)","1.png",'0px','0px'],
            dom:[
                {
                    id:"img_1",
                    type:"image",
                    rect:[],
                    fill:["rgba(0,0,0,0)","page_1_1.png",'0px','0px'],
                    animate:["bottom",-130,380,true,600]
                },
                {
                    id:"group_1",
                    type:"group",
                    rect:[],
                    fill:[],
                    animate:[],
                    dom:[]
                },
                {
                    id:"img_2",
                    type:"image",
                    rect:[],
                    fill:["rgba(0,0,0,0)","page_1_2.png",'0px','0px'],
                    animate:["bottom",-120,310,true,600]
                }
            ]
        },
        {
            id:"page_2",
            config:{},
            fill:["rgba(0,0,0,0)","1.png",'0px','0px'],
            dom:[]
        },
        {
            id:"page_3",
            config:{},
            fill:["rgba(0,0,0,0)","1.png",'0px','0px'],
            dom:[]
        },
        {
            id:"page_4",
            config:{},
            fill:["rgba(0,0,0,0)","bg_1.jpg",'0px','0px'],
            dom:[]
        },
        {
            id:"page_5",
            config:{},
            fill:["rgba(255,0,0,1)",null,'0px','0px'],
            dom:[]
        }
    ]
}